= Using of kysely for DB acccess
Richard Attermeyer
v25.1, 11.03.2025: Initial Version
:summary: Using kysely for DB access
:keywords: DB, postgres, query builder, ORM
// Who approved the proposal (team, architect, ...(individual or team))
:approvers: Richard
// Who provided input into the preparation of this ADR?
:contributors: Richard
// Who must be informed about the changes?
// Examples: Team | Operations | Project Management | ...
:informed: Team
// STATUS: PROPOSED | ACCEPTED | REPLACED | REJECTED
:status: ACCEPTED
:superseded-by:
:next-review-after:
:next-review-before:

[cols="1h,3"]
|===
| Version | {page-component-version}
ifdef::revremark[]
|Status |*{status}*
| Revision Comment | {revremark}
endif::[]
ifdef::page-origin-refhash[]
| Commit | {page-origin-refhash}
endif::[]
ifdef::page-origin-tag[]
| Tag | {page-origin-tag}
endif::[]
ifdef::page-origin-url[]
| Repository | {page-origin-url}
endif::[]

|Last Re-evaluation
|{revnumber} - {revdate}

|Last Reviewers
|{authors}

|Contributors
|{contributors}

|Informed
|{informed}

|Keywords
|{keywords}

ifdef::superseded-by[]
|Superseded by
|{superseded-by}
endif::[]
|===

== Context and Problem Statement

Database access should also be type-safe and type checking should highlight issues,
if queries do not match to the configured DB schema.

== Architectural Drivers

* Database First development philosophy
* Type Safety
* Postgres Database

== Decision

[IMPORTANT]
*Using kysely for DB access*

Kysely, currently seems to be the most typesafe option, as shown in the https://github.com/thetutlage/meta/discussions/8[github issue].
Furthermore, kysely also supports Oracle through a https://github.com/griffiths-waite/kysely-oracledb[community dialect].

=== Relationship to other Architectural Decisions
////
Binde hier ein Diagramm ein, dass den Zusammenhang mit anderen Architekturkomponenten darstellt.
Dies gilt erst mal nur für das in diesem Zusammenhang betrachtete Flavour
////

== Consequences

////
Beschreibe hier die Konsequenzen (positive wie negative) der aktuellen Entscheidung.
Keine Entscheidung hat nur positive Effekte.
////

== Considered Alternatives

=== drizzle ORM
////
Liste hier die einzelnen Alternativen auf und begründe, warum die Alternative aktuell verworfen wurde
////

As put in the github issue:

[quote]
Drizzle gives the impression of type-safety. However, only the query results have type information. You can write invalid queries with Drizzle.

However, drizzle orm has the advantage of supporting https://orm.drizzle.team/docs/rls[row-level-security] in postgres.
This might be important, if you need RLS, e.g. for multi-tenancy.

This is at least valid, if you use Postgres as a database.

drizzle on the other hand does not support Oracle.



