/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntityModelCustomer } from './EntityModelCustomer';
import {
    EntityModelCustomerFromJSON,
    EntityModelCustomerFromJSONTyped,
    EntityModelCustomerToJSON,
    EntityModelCustomerToJSONTyped,
} from './EntityModelCustomer';

/**
 * 
 * @export
 * @interface CollectionModelEntityModelCustomerEmbedded
 */
export interface CollectionModelEntityModelCustomerEmbedded {
    /**
     * 
     * @type {Array<EntityModelCustomer>}
     * @memberof CollectionModelEntityModelCustomerEmbedded
     */
    customers?: Array<EntityModelCustomer>;
}

/**
 * Check if a given object implements the CollectionModelEntityModelCustomerEmbedded interface.
 */
export function instanceOfCollectionModelEntityModelCustomerEmbedded(value: object): value is CollectionModelEntityModelCustomerEmbedded {
    return true;
}

export function CollectionModelEntityModelCustomerEmbeddedFromJSON(json: any): CollectionModelEntityModelCustomerEmbedded {
    return CollectionModelEntityModelCustomerEmbeddedFromJSONTyped(json, false);
}

export function CollectionModelEntityModelCustomerEmbeddedFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionModelEntityModelCustomerEmbedded {
    if (json == null) {
        return json;
    }
    return {
        
        'customers': json['customers'] == null ? undefined : ((json['customers'] as Array<any>).map(EntityModelCustomerFromJSON)),
    };
}

export function CollectionModelEntityModelCustomerEmbeddedToJSON(json: any): CollectionModelEntityModelCustomerEmbedded {
    return CollectionModelEntityModelCustomerEmbeddedToJSONTyped(json, false);
}

export function CollectionModelEntityModelCustomerEmbeddedToJSONTyped(value?: CollectionModelEntityModelCustomerEmbedded | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'customers': value['customers'] == null ? undefined : ((value['customers'] as Array<any>).map(EntityModelCustomerToJSON)),
    };
}

