/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CollectionModelEntityModelCustomerEmbedded } from './CollectionModelEntityModelCustomerEmbedded';
import {
    CollectionModelEntityModelCustomerEmbeddedFromJSON,
    CollectionModelEntityModelCustomerEmbeddedFromJSONTyped,
    CollectionModelEntityModelCustomerEmbeddedToJSON,
    CollectionModelEntityModelCustomerEmbeddedToJSONTyped,
} from './CollectionModelEntityModelCustomerEmbedded';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
    LinkToJSONTyped,
} from './Link';

/**
 * 
 * @export
 * @interface CollectionModelEntityModelCustomer
 */
export interface CollectionModelEntityModelCustomer {
    /**
     * 
     * @type {CollectionModelEntityModelCustomerEmbedded}
     * @memberof CollectionModelEntityModelCustomer
     */
    embedded?: CollectionModelEntityModelCustomerEmbedded;
    /**
     * 
     * @type {{ [key: string]: Link; }}
     * @memberof CollectionModelEntityModelCustomer
     */
    links?: { [key: string]: Link; };
}

/**
 * Check if a given object implements the CollectionModelEntityModelCustomer interface.
 */
export function instanceOfCollectionModelEntityModelCustomer(value: object): value is CollectionModelEntityModelCustomer {
    return true;
}

export function CollectionModelEntityModelCustomerFromJSON(json: any): CollectionModelEntityModelCustomer {
    return CollectionModelEntityModelCustomerFromJSONTyped(json, false);
}

export function CollectionModelEntityModelCustomerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionModelEntityModelCustomer {
    if (json == null) {
        return json;
    }
    return {
        
        'embedded': json['_embedded'] == null ? undefined : CollectionModelEntityModelCustomerEmbeddedFromJSON(json['_embedded']),
        'links': json['_links'] == null ? undefined : (mapValues(json['_links'], LinkFromJSON)),
    };
}

export function CollectionModelEntityModelCustomerToJSON(json: any): CollectionModelEntityModelCustomer {
    return CollectionModelEntityModelCustomerToJSONTyped(json, false);
}

export function CollectionModelEntityModelCustomerToJSONTyped(value?: CollectionModelEntityModelCustomer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_embedded': CollectionModelEntityModelCustomerEmbeddedToJSON(value['embedded']),
        '_links': value['links'] == null ? undefined : (mapValues(value['links'], LinkToJSON)),
    };
}

