// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { uuid, type Uuid } from './Role';
import { z } from 'zod';

/** Represents the table chinook.account_role */
export interface AccountRole {
  /** Database type: pg_catalog.uuid */
  accountUuid: Uuid;

  /** Database type: pg_catalog.uuid */
  roleUuid: Uuid;
}

/** Represents the initializer for the table chinook.account_role */
export interface AccountRoleInitializer {
  /** Database type: pg_catalog.uuid */
  accountUuid: Uuid;

  /** Database type: pg_catalog.uuid */
  roleUuid: Uuid;
}

/** Represents the mutator for the table chinook.account_role */
export interface AccountRoleMutator {
  /** Database type: pg_catalog.uuid */
  accountUuid?: Uuid;

  /** Database type: pg_catalog.uuid */
  roleUuid?: Uuid;
}

export const accountRole = z.object({
  accountUuid: uuid,
  roleUuid: uuid,
}) as unknown as z.Schema<AccountRole>;

export const accountRoleInitializer = z.object({
  accountUuid: uuid,
  roleUuid: uuid,
}) as unknown as z.Schema<AccountRoleInitializer>;

export const accountRoleMutator = z.object({
  accountUuid: uuid.optional(),
  roleUuid: uuid.optional(),
}) as unknown as z.Schema<AccountRoleMutator>;
