// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from "zod";

/** Represents the view chinook.album_view */
export interface AlbumView {
	/** Database type: pg_catalog.varchar */
	title: string;

	/** Database type: pg_catalog.varchar */
	artist: string;

	/** Database type: pg_catalog.int8 */
	numberOfTracks: bigint;

	/** Database type: pg_catalog.int8 */
	lengthMilliseconds: bigint;

	/** Database type: pg_catalog.int8 */
	lengthSeconds: bigint;

	/** Database type: pg_catalog.int8 */
	lengthMinutes: bigint;

	/** Database type: pg_catalog.int4 */
	artistId: number;

	/** Database type: pg_catalog.int4 */
	albumId: number;
}

export const albumView = z.object({
	title: z.string(),
	artist: z.string(),
	numberOfTracks: z.string(),
	lengthMilliseconds: z.string(),
	lengthSeconds: z.string(),
	lengthMinutes: z.string(),
	artistId: z.number(),
	albumId: z.number(),
}) as unknown as z.Schema<AlbumView>;
