// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from 'zod';

/** Represents the view chinook.album_tracks */
export interface AlbumTracks {
  /** Database type: pg_catalog.varchar */
  albumTitle: string;

  /** Database type: pg_catalog.varchar */
  artistName: string;

  /** Database type: pg_catalog.varchar */
  trackName: string;

  /** Database type: pg_catalog.varchar */
  genreName: string;

  /** Database type: pg_catalog.int4 */
  milliseconds: number;

  /** Database type: pg_catalog.int4 */
  albumId: number;

  /** Database type: pg_catalog.int4 */
  artistId: number;

  /** Database type: pg_catalog.int4 */
  trackId: number;

  /** Database type: pg_catalog.int4 */
  genreId: number;
}

export const albumTracks = z.object({
  albumTitle: z.string(),
  artistName: z.string(),
  trackName: z.string(),
  genreName: z.string(),
  milliseconds: z.number(),
  albumId: z.number(),
  artistId: z.number(),
  trackId: z.number(),
  genreId: z.number(),
}) as unknown as z.Schema<AlbumTracks>;
