// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from "zod";

/** Represents the view chinook.customer_view */
export interface CustomerView {
	/** Database type: pg_catalog.text */
	customerName: string;

	/** Database type: pg_catalog.varchar */
	firstName: string;

	/** Database type: pg_catalog.varchar */
	lastName: string;

	/** Database type: pg_catalog.varchar */
	company: string;

	/** Database type: pg_catalog.varchar */
	address: string;

	/** Database type: pg_catalog.varchar */
	city: string;

	/** Database type: pg_catalog.varchar */
	state: string;

	/** Database type: pg_catalog.varchar */
	country: string;

	/** Database type: pg_catalog.varchar */
	postalCode: string;

	/** Database type: pg_catalog.varchar */
	phone: string;

	/** Database type: pg_catalog.varchar */
	fax: string;

	/** Database type: pg_catalog.varchar */
	email: string;

	/** Database type: pg_catalog.text */
	supportRepName: string;

	/** Database type: pg_catalog.int4 */
	supportRepId: number;

	/** Database type: pg_catalog.int4 */
	customerId: number;
}

export const customerView = z.object({
	customerName: z.string(),
	firstName: z.string(),
	lastName: z.string(),
	company: z.string(),
	address: z.string(),
	city: z.string(),
	state: z.string(),
	country: z.string(),
	postalCode: z.string(),
	phone: z.string(),
	fax: z.string(),
	email: z.string(),
	supportRepName: z.string(),
	supportRepId: z.number(),
	customerId: z.number(),
}) as unknown as z.Schema<CustomerView>;
