// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from "zod";

/** Represents the view chinook.invoice_line_view */
export interface InvoiceLineView {
	/** Database type: pg_catalog.int4 */
	invoiceLineId: number;

	/** Database type: pg_catalog.varchar */
	trackName: string;

	/** Database type: pg_catalog.int4 */
	quantity: number;

	/** Database type: pg_catalog.numeric */
	unitPrice: string;

	/** Database type: pg_catalog.int4 */
	invoiceId: number;

	/** Database type: pg_catalog.numeric */
	price: string;
}

export const invoiceLineView = z.object({
	invoiceLineId: z.number(),
	trackName: z.string(),
	quantity: z.number(),
	unitPrice: z.string(),
	invoiceId: z.number(),
	price: z.string(),
}) as unknown as z.Schema<InvoiceLineView>;
