// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from "zod";

/** Represents the view chinook.invoice_view */
export interface InvoiceView {
	/** Database type: pg_catalog.int4 */
	invoiceId: number;

	/** Database type: pg_catalog.timestamp */
	invoiceDate: Date;

	/** Database type: pg_catalog.text */
	customerName: string;

	/** Database type: pg_catalog.int4 */
	customerId: number;

	/** Database type: pg_catalog.numeric */
	total: string;

	/** Database type: pg_catalog.varchar */
	billingAddress: string;

	/** Database type: pg_catalog.varchar */
	billingPostalCode: string;

	/** Database type: pg_catalog.varchar */
	billingCity: string;

	/** Database type: pg_catalog.varchar */
	billingState: string;

	/** Database type: pg_catalog.varchar */
	billingCountry: string;
}

export const invoiceView = z.object({
	invoiceId: z.number(),
	invoiceDate: z.date(),
	customerName: z.string(),
	customerId: z.number(),
	total: z.string(),
	billingAddress: z.string(),
	billingPostalCode: z.string(),
	billingCity: z.string(),
	billingState: z.string(),
	billingCountry: z.string(),
}) as unknown as z.Schema<InvoiceView>;
