// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from "zod";
import { type PlaylistId, playlistId } from "./Playlist";
import { type TrackId, trackId } from "./Track";

/** Represents the table chinook.playlist_track */
export interface PlaylistTrack {
	/** Database type: pg_catalog.int4 */
	playlistId: PlaylistId;

	/** Database type: pg_catalog.int4 */
	trackId: TrackId;
}

/** Represents the initializer for the table chinook.playlist_track */
export interface PlaylistTrackInitializer {
	/** Database type: pg_catalog.int4 */
	playlistId: PlaylistId;

	/** Database type: pg_catalog.int4 */
	trackId: TrackId;
}

/** Represents the mutator for the table chinook.playlist_track */
export interface PlaylistTrackMutator {
	/** Database type: pg_catalog.int4 */
	playlistId?: PlaylistId;

	/** Database type: pg_catalog.int4 */
	trackId?: TrackId;
}

export const playlistTrack = z.object({
	playlistId: playlistId,
	trackId: trackId,
}) as unknown as z.Schema<PlaylistTrack>;

export const playlistTrackInitializer = z.object({
	playlistId: playlistId,
	trackId: trackId,
}) as unknown as z.Schema<PlaylistTrackInitializer>;

export const playlistTrackMutator = z.object({
	playlistId: playlistId.optional(),
	trackId: trackId.optional(),
}) as unknown as z.Schema<PlaylistTrackMutator>;
