// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from "zod";

/** Identifier type for playlist */
export type PlaylistId = number & { __flavor?: "PlaylistId" };

/** Represents the table chinook.playlist */
export interface Playlist {
	/** Database type: pg_catalog.int4 */
	playlistId: PlaylistId;

	/** Database type: pg_catalog.varchar */
	name: string | null;
}

/** Represents the initializer for the table chinook.playlist */
export interface PlaylistInitializer {
	/**
	 * Database type: pg_catalog.int4
	 * Default value: nextval('playlist_playlist_id_seq'::regclass)
	 */
	playlistId?: PlaylistId;

	/** Database type: pg_catalog.varchar */
	name?: string | null;
}

/** Represents the mutator for the table chinook.playlist */
export interface PlaylistMutator {
	/** Database type: pg_catalog.int4 */
	playlistId?: PlaylistId;

	/** Database type: pg_catalog.varchar */
	name?: string | null;
}

export const playlistId = z.number() as unknown as z.Schema<PlaylistId>;

export const playlist = z.object({
	playlistId: playlistId,
	name: z.string().nullable(),
}) as unknown as z.Schema<Playlist>;

export const playlistInitializer = z.object({
	playlistId: playlistId.optional(),
	name: z.string().optional().nullable(),
}) as unknown as z.Schema<PlaylistInitializer>;

export const playlistMutator = z.object({
	playlistId: playlistId.optional(),
	name: z.string().optional().nullable(),
}) as unknown as z.Schema<PlaylistMutator>;
