// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from "zod";

/** Represents the view chinook.sales_agent_view */
export interface SalesAgentView {
	/** Database type: pg_catalog.text */
	name: string;

	/** Database type: pg_catalog.varchar */
	firstName: string;

	/** Database type: pg_catalog.varchar */
	lastName: string;

	/** Database type: pg_catalog.varchar */
	phone: string;

	/** Database type: pg_catalog.varchar */
	email: string;

	/** Database type: pg_catalog.varchar */
	fax: string;

	/** Database type: pg_catalog.int4 */
	employeeId: number;
}

export const salesAgentView = z.object({
	name: z.string(),
	firstName: z.string(),
	lastName: z.string(),
	phone: z.string(),
	email: z.string(),
	fax: z.string(),
	employeeId: z.number(),
}) as unknown as z.Schema<SalesAgentView>;
