= Nutzung von XXXX für YYYY
Max Mustermann
v00.0, 1.1.1970: Initialerstellung
:summary: Kurze Zusammenfassung
:keywords: <keyword1>, <keyword2>, ...
// Who approved the proposal (team, architect, ...(individual or team))
:approvers: Big Boss (Solution Architekt)
// Who provided input into the preparation of this ADR?
:contributors: Alice, Bob
// Who must be informed about the changes?
// Examples: Team | Operations | Project Management | ...
:informed: Team
// STATUS: PROPOSED | ACCEPTED | REPLACED | REJECTED
:status: PROPOSED
:superseded-by:
:next-review-after:
:next-review-before:

[cols="1h,3"]
|===
| Version | {page-component-version}
ifdef::revremark[]
|Status |*{status}*
| Revision Kommentar | {revremark}
endif::[]
ifdef::page-origin-refhash[]
| Commit | {page-origin-refhash}
endif::[]
ifdef::page-origin-tag[]
| Tag | {page-origin-tag}
endif::[]
ifdef::page-origin-url[]
| Repository | {page-origin-url}
endif::[]

|Letzte Reevaluation
|{revnumber} - {revdate}

|Letzte Reviewer
|{authors}

|Mitwirkende
|{contributors}

|Zu informieren
|{informed}

|Schlagworte
|{keywords}

ifdef::superseded-by[]
|Ersetzt durch
|{superseded-by}
endif::[]
|===

== Kontext und Problembeschreibung

////
Beschreibe hier den Kontext und das Problem für das eine Entscheidung herbeigeführt werden muss
////

== Architekturtreiber und Glaubenssätze

////
Liste alle für die Entscheidung relevanten Architekturtreiber bzw. Glaubenssätze auf.
Da wir "nur" eine Standardarchitektur definieren, kennen wir nicht kundenspezifische Architekturtreiber.
Daher müssen wir uns mit Glaubenssätzen behelfen
////

== Entscheidung

[IMPORTANT]
*Nutzung von <Tool / Framework >*

////
Begründe im Folgenden die Entscheidung.
Eine Begründung kann sich auf das OC Partnerökosystem beziehen oder die Verwendung und Passung in
andere Aufgabenstellungen im aktuell betrachteten Architekturflavour.
Berücksichtige dabei auch die anderen Standardarchitekturen
////

=== Zusammenhang mit anderen Entscheidungen
////
Binde hier ein Diagramm ein, dass den Zusammenhang mit anderen Architekturkomponenten darstellt.
Dies gilt erst mal nur für das in diesem Zusammenhang betrachtete Flavour
////

== Konsequenzen

////
Beschreibe hier die Konsequenzen (positive wie negative) der aktuellen Entscheidung.
Keine Entscheidung hat nur positive Effekte.
////

== Betrachtete Alternativen

=== Alternative 1
////
Liste hier die einzelnen Alternativen auf und begründe, warum die Alternative aktuell verworfen wurde
////




